### ISSUE TITLE
aggregator: jobs with collections on multiple backends

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-aggregator#115]

**Comment by soxofaan** [comment]
builds further on https://github.com/Open-EO/openeo-aggregator/issues/95

**Comment by soxofaan** [comment]
already merged current state in master (feature has to be enabled with feature flag `job_options={"split_strategy": "crossbackend"}`)

Still to do, follow-up features and related issues to look into:
- automatically detect need for and enable this cross-backend  mode
- https://github.com/Open-EO/openeo-api/issues/507
- https://github.com/Open-EO/openeo-api/issues/508
- https://github.com/Open-EO/openeo-geopyspark-driver/issues/505
- https://github.com/Open-EO/openeo-geopyspark-driver/issues/507
- current implementation only considers availability of collection ids, also handle process ids?
- smarter splitting than 'just split off each "alien" load_collection' node, make subgraphs largers?

**Comment by jdries** [comment]
reached initial goal, so closing!
