### ISSUE TITLE
`datacube` - `rastercube` inconsistencies

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-aggregator#118]
reported by @EmileSonneveld :

linking `load_collection` with `filter_bbox` in the openeo.cloud editor raises a warning

> incoming data type is not compatible for parameter "data"

![image](https://github.com/Open-EO/openeo-aggregator/assets/44946/d5f5cc5f-598e-4000-b3d5-919747c8be3e)

return type of `load_collection` is indeed `raster-cube`, while `filter_bbox` expects a `datacube`

**Comment by soxofaan** [comment]
- problem does not occur when doing same exercise directly on VITO backend , (https://openeo.vito.be/openeo/1.1)
- problem can also be reproduced on EODC backend at https://openeo.eodc.eu/openeo/1.1.0  (CC @LukeWeidenwalker )

**Comment by soxofaan** [comment]
quick snippet to double check current schemas of openeo.cloud and related back-ends:

```python
import openeo
import pprint

for url in [
    "openeo.cloud",
    "openeo.vito.be/openeo/1.1/",
    "openeo.eodc.eu/openeo/1.1.0/",
    "openeo.sentinel-hub.com/production/",
]:
    print("###", url)
    connection = openeo.connect(url)
    lc = connection.describe_process("load_collection")["returns"]["schema"]
    fb = connection.describe_process("filter_bbox")["parameters"][0]["schema"]
    print("load_collection return", pprint.pformat(lc))
    print("filter_bbox input     ", pprint.pformat(fb))
```
```
### openeo.cloud
load_collection return {'subtype': 'raster-cube', 'type': 'object'}
filter_bbox input      [{'dimensions': [{'axis': ['x', 'y'], 'type': 'spatial'}],
  'subtype': 'datacube',
  'title': 'Raster data cube',
  'type': 'object'},
 {'dimensions': [{'type': 'geometry'}],
  'subtype': 'datacube',
  'title': 'Vector data cube',
  'type': 'object'}]
### openeo.vito.be/openeo/1.1/
load_collection return {'subtype': 'raster-cube', 'type': 'object'}
filter_bbox input      {'subtype': 'raster-cube', 'type': 'object'}
### openeo.eodc.eu/openeo/1.1.0/
load_collection return {'subtype': 'raster-cube', 'type': 'object'}
filter_bbox input      [{'dimensions': [{'axis': ['x', 'y'], 'type': 'spatial'}],
  'subtype': 'datacube',
  'title': 'Raster data cube',
  'type': 'object'},
 {'dimensions': [{'type': 'geometry'}],
  'subtype': 'datacube',
  'title': 'Vector data cube',
  'type': 'object'}]
### openeo.sentinel-hub.com/production/
load_collection return {'subtype': 'raster-cube', 'type': 'object'}
filter_bbox input      {'subtype': 'raster-cube', 'type': 'object'}


```

**Comment by soxofaan** [comment]
This was pretty confusing as the aggregator in most cases gives precedence to VITO metadata over EODC metadata if there is a difference, so I didn't understand how EODC metadata surfaced here in this case.
Turns out that 60f2de4869308db887b006fac4f7ae60dfa18bc6 introduced a different precedence order (based on alphabetical ordering of backend ids) giving EODC higher precedence over VITO.

**Comment by soxofaan** [comment]
restored the general back-end precedence rule.

I think that solves the problem at level of aggregator. 

Further datacube/rastercube schema inconsistencies are matter for upstream back-ends

**Comment by EmileSonneveld** [comment]
The same error is also visible with `resample_spatial` on https://openeo.cloud:
![image](https://github.com/Open-EO/openeo-aggregator/assets/2298426/d5fadc89-3fc5-42c2-9b12-b9d97c78fc21)
I guess it will be fixed with the next deployment
