### ISSUE TITLE
ciritcal worker timeout

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-aggregator#15]
related to https://github.com/openEOPlatform/architecture-docs/issues/99 and https://github.com/openEOPlatform/architecture-docs/issues/110

Part of problem is that gunicorn kills workers after a timeout:
```
[2021-10-11 14:01:59 +0200] [22797] [CRITICAL] WORKER TIMEOUT (pid:22801)
```

default is 30s: https://docs.gunicorn.org/en/stable/settings.html?highlight=when_ready#timeout

sould be increased

**Comment by clausmichele** [comment]
Oh, I've experienced a similar issue months ago in our set-up at Eurac, where I've also increased the timeout.
