### ISSUE TITLE
Data missing from job listing

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-aggregator#45]
The job listing from the aggregator is very slim, it only lists id, created, updated and status. The API docs states:

> It is strongly RECOMMENDED to keep the response size small by omitting all optional non-scalar values from objects in jobs (i.e. the process property). 

So I'd expect all scalars to be present. Most importantly, I think the title should be provided. Otherwise, the Job tables in the clients look like this:
![image](https://user-images.githubusercontent.com/8262166/165544884-9e8e1826-0c26-46a4-a5e9-f5a9a67e7c8d.png)

This is not very user-friendly. The back-ends themselves provide e.g. the title.

**Comment by soxofaan** [comment]
The aggregator does not actively slim down job listings it gets from upstream, 
it basically copies over all standard job fields that are available. If title is present in the upstream listing, it will be present in the aggregator response.

For example, see this test:
https://github.com/Open-EO/openeo-aggregator/blob/163156fadd9e36df271e8f01c39a8a02b4f21ad6/tests/test_views.py#L613-L630

Do you have more concrete cases where there is data loss at the aggregator level?

**Comment by m-mohr** [comment]
Connecting directly to the vito back-end returns titles:

![image](https://user-images.githubusercontent.com/8262166/166416395-a8d6bf0e-218a-42e6-a77b-caf1a59dc1b6.png)

**Comment by m-mohr** [comment]
JSON responses for comparison:

Aggregator (removed EODC):
```json
{
  "jobs": [
    {
      "created": "2022-04-22T15:46:32Z",
      "id": "vito-1560b744-e3dd-4be1-bb76-e426a0cc45ea",
      "status": "error",
      "updated": "2022-04-22T16:02:22Z"
    },
    {
      "created": "2022-04-19T10:19:51Z",
      "id": "vito-d714cd6a-21e7-416a-b099-e880f5570568",
      "status": "finished",
      "updated": "2022-04-19T10:24:30Z"
    },
    {
      "created": "2022-04-22T08:20:19Z",
      "id": "vito-adc169e2-4a56-4021-878f-a404924583a7",
      "status": "finished",
      "updated": "2022-04-22T08:24:37Z"
    },
    {
      "created": "2022-04-14T12:05:17Z",
      "id": "vito-552e3e33-4fe0-42ca-b93c-7f1cd3a91224",
      "status": "finished",
      "updated": "2022-04-14T12:05:50Z"
    },
    {
      "created": "2022-04-19T15:31:13Z",
      "id": "vito-15a2bbc1-f53e-4bf5-bc87-00a37e78b3ac",
      "status": "finished",
      "updated": "2022-04-19T15:31:57Z"
    },
    {
      "created": "2022-04-22T10:24:51Z",
      "id": "vito-1925b816-ed2b-423c-ad72-49b1d3e4df7c",
      "status": "finished",
      "updated": "2022-04-22T10:29:57Z"
    },
    {
      "created": "2022-04-19T10:20:32Z",
      "id": "vito-8ce3a703-5a6d-4e80-b3f3-e90ebe620836",
      "status": "finished",
      "updated": "2022-04-19T10:25:06Z"
    }
  ],
  "links": []
}
```

VITO:
```json
{
  "jobs": [
    {
      "created": "2022-04-22T15:46:32Z",
      "id": "1560b744-e3dd-4be1-bb76-e426a0cc45ea",
      "status": "error",
      "title": "L8 smaller island",
      "updated": "2022-04-22T16:02:22Z"
    },
    {
      "created": "2022-04-19T10:19:51Z",
      "id": "d714cd6a-21e7-416a-b099-e880f5570568",
      "status": "finished",
      "title": "rgb  island",
      "updated": "2022-04-19T10:24:30Z"
    },
    {
      "created": "2022-04-22T08:20:19Z",
      "id": "adc169e2-4a56-4021-878f-a404924583a7",
      "status": "finished",
      "title": "rgb island wgs84 w/o ovr",
      "updated": "2022-04-22T08:24:37Z"
    },
    {
      "created": "2022-04-14T12:05:17Z",
      "id": "552e3e33-4fe0-42ca-b93c-7f1cd3a91224",
      "status": "finished",
      "title": "island",
      "updated": "2022-04-14T12:05:50Z"
    },
    {
      "created": "2022-04-19T15:31:13Z",
      "id": "15a2bbc1-f53e-4bf5-bc87-00a37e78b3ac",
      "status": "finished",
      "title": "yearly ndvi 2",
      "updated": "2022-04-19T15:31:57Z"
    },
    {
      "created": "2022-04-22T10:24:51Z",
      "id": "1925b816-ed2b-423c-ad72-49b1d3e4df7c",
      "status": "finished",
      "title": "rgb island smaller",
      "updated": "2022-04-22T10:29:57Z"
    },
    {
      "created": "2022-04-19T10:20:32Z",
      "id": "8ce3a703-5a6d-4e80-b3f3-e90ebe620836",
      "status": "finished",
      "title": "coastal",
      "updated": "2022-04-19T10:25:06Z"
    }
  ],
  "links": []
}
```

The titles are obviously missing in the aggregator. Does this help @soxofaan ?

**Comment by m-mohr** [comment]
By the way, it seems the aggragetor connects to https://openeo.vito.be/openeo/1.0/ while the Web Editor connects to https://openeo.vito.be/openeo/1.1/ - but both instances return titles so that shouldn't be the difference.

**Comment by soxofaan** [comment]
> The titles are obviously missing in the aggregator. Does this help @soxofaan ?

When testing against dev instance openeocloud-dev.vito.be, it title issue seems to be fixed, so this is just a matter of promoting a recent build to production.

> By the way, it seems the aggragetor connects to https://openeo.vito.be/openeo/1.0/ while the Web Editor connects to https://openeo.vito.be/openeo/1.1/ - but both instances return titles so that shouldn't be the difference.

Indeed, that shouldn't make a difference

**Comment by soxofaan** [comment]
just promoted latest build to production and that seems to fix the issue as far as I could test.

can you confirm?

(I'll already close)

**Comment by m-mohr** [comment]
Yes, works for me, too! Thanks, that is very useful for LPS!
