### ISSUE TITLE
aggregator error on user defined processes lookup

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-aggregator#48]
https://openeocloud.vito.be/openeo/1.0/processes/u:driesj

=>

"'NoneType' object has no attribute 'get_for_user'"

**Comment by soxofaan** [comment]
closing this for now

through improvement in openeo_driver, the error will now be less cryptic:
```
$ curl https://openeocloud-dev.vito.be/openeo/1.0/processes/u:driesj
{"code":"Internal","id":"db48de40-47cf-4197-a609-d3a904021290","message":"Could not handle namespace 'u:driesj'"}

```
