### ISSUE TITLE
random forest: providing training job with aggregator job id fails

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-aggregator#70]
When referencing a random forest by job id, this doesn't work:
training_job = c.job("vito-j-cc66a593416043468e4c5ca83ef90b28")
it gives an error when trying to apply random forest.

This does work:
training_job = c.job("j-cc66a593416043468e4c5ca83ef90b28")

probably the 'vito-' prefix needs to be stripped automatically.

**Comment by soxofaan** [comment]
done
