### ISSUE TITLE
/service_types: skip backend when its capabilities states it does not support /service_types

### ISSUE THREAD

**Issue by JohanKJSchreurs** [Open-EO/openeo-aggregator#85]
EODC backend (e.g.) does not support /service_types and we can know that beforehand (because it's not in capabilities doc), so we should skip it, instead of trying and needlessly logging a 404 error.

This is a follow up ticket for the to do's of https://github.com/Open-EO/openeo-aggregator/issues/78, to plan and track the tasks separately .
See also: https://github.com/Open-EO/openeo-aggregator/issues/78#issuecomment-1326180557

**Comment by soxofaan** [comment]
FYI: VITO back-end also stopped supporting /service_types since https://github.com/Open-EO/openeo-geopyspark-driver/commit/c61b822d99eb5c7e26d86b10ef155c2df4a3950f  (I'm not sure if this change is in production already)

**Comment by soxofaan** [comment]
some info:

Start from a `MultiBackendConnection` and iterate through the upstream backends (`BackendConnection` objects), each of these has a `capabilities()` method, which returns an `RESTCapabilities` object. From that you should be able to check with `supports_endpoint`  if  `/service_types` is supported

**Comment by soxofaan** [comment]
another thing: I think it makes sense to store the result of this check in the housekeeping structure mentioned in #84 in some way

**Comment by soxofaan** [comment]
#87 was merged
