### ISSUE TITLE
UDP support (`/process_graphs`)

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-aggregator#90]
Add support for UDPs (`GET /process_graphs` and related).

Questions:
- where to store? at level of aggregator, or "highest prio" upstream back-end, or all backends?
- what to list? only UDPs defined at aggregator or combine multiple upstream back-ends?
- how to handle job with UDP usage if UDPs are stored only at level of aggregator? Automatically store UDP in upstream back-end first, or rewrite "UDP calls" in original process graph with actual UDP implementation?

**Comment by m-mohr** [comment]
The details have to be discussed, but the most important thing is that files and user-defined processes must be accessible by all back-ends in the federation because otherwise, users can't re-use them properly in other processes. User shouldn't need to care about where something is available and where it's not available.

**Comment by patrick-griffiths** [comment]
@m-mohr @soxofaan @jdries 
UPD support by the aggregator is important for the platform part!  
Could we add a task as part of SAP09 Operationalization on this?

**Comment by soxofaan** [comment]
We just added very basic support to the aggregator (just on dev instance openeocloud-dev.vito.be at the moment):
UDP interactions are just proxied directly to VITO back-end: creating, getting, listing UDPs on the aggregator goes directly to VITO UDP storage.

This is not ideal because there is no federation aspect to this, but at least the basics are working for majority of processing requests (which go to VITO anyway)

**Comment by soxofaan** [comment]
basic implementation is available, will close this ticket.

Follow-up is for https://github.com/openEOPlatform/architecture-docs/issues/368
